### PR TITLE
Update wise.conf

### PR DESCRIPTION
**Pull request by VM8gkAs**
Refactored Nginx config by replacing hardcoded service URLs with variables for better maintainability and flexibility.

    Added variables:
        $w_client = http://wise-client:4200
        $w_api = http://wise-api:8080
    Replaced hardcoded URLs with $w_client and $w_api throughout the config.

### CODE REVIEW

**Comment by hirokiterashima** [comment]
It looks like your changes should work, but when I check out the changes, restart Docker, and go to the homepage, I see 502 Bad Gateway error page in the browser and this in the console:
```
...
wise-nginx   | 2024/09/13 22:01:57 [error] 20#20: *1 no resolver defined to resolve wise-client, client: 192.168.65.1, server: , request: "GET / HTTP/1.1", host: "localhost:81"
wise-nginx   | 2024/09/13 22:01:57 [error] 20#20: *1 no resolver defined to resolve wise-client, client: 192.168.65.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:81", referrer: "http://localhost:81/"
...
```

Any ideas?

**Comment by VM8gkAs** [comment]
Sorry, I forgot to add the line
`resolver 127.0.0.11;`
above the line
`set $w_client = http://wise-client:4200;`
, which indicates using "Docker's internal DNS server." This should solve the problem.

As for the GitHub Pull operation, I'm not very familiar with it. Do I need to close the pull request?

**Comment by hirokiterashima** [comment]
No worries. Go ahead and make the change, commit to your patch-1 branch and push. That should update this PR, and I can test out your changes as you intended. If everything looks good, I will approve it and merge your changes to this repo.

**Review by hirokiterashima — APPROVED** [review]
LGTM

**Pull request merged**
